version: "3"

services:
    front-end:
        build:
            context: .\frontend\
        restart: unless-stopped
        ports:
         - "3000:3000"
    nginx:
        image: nginx:latest
        restart: unless-stopped
        build: .
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - userservice
            - postservice


    sqlite3:
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - ./db/:/root/db/
            
    userservice:
        build: ./user
        restart: unless-stopped
        depends_on:
            - userdb

    userdb:
        image: nouchka/sqlite3:latest  # Use the SQLite3 image
        stdin_open: true
        tty: true
        volumes:
            - /sqlite:/data/db
        restart: unless-stopped

    postservice:
        build: ./post
        restart: unless-stopped
        depends_on:
            - postdb
            - postobjectdb

    postdb:
        image: nouchka/sqlite3:latest  # Use the SQLite3 image
        stdin_open: true
        tty: true
        volumes:
            - /sqlite:/data/db
        restart: unless-stopped

    postobjectdb:
        image: minio/minio:latest
        environment:
            - MINIO_ACCESS_KEY=5rv9URqyQUpPokY9voaC
            - MINIO_SECRET_KEY=3Prm4KHtfRu3JSo15S50ceyq6dIJ957RrziixTj1
        command: server --address 0.0.0.0:9000 /data
